### ISSUE TITLE
Request: Check PR Author Instead of Action Actor

### ISSUE THREAD

**Issue by jackson-miller-tbol** [dependabot/fetch-metadata#112]
https://github.com/dependabot/fetch-metadata/blob/ffa0846490b6178282839adcc9f50954b247e373/src/dependabot/verified_commits.ts#L20-L24

The above code seems to check whether or not the Actions actor is Dependabot and avoids calling the API if the actor isn't Dependabot.   Can we consider checking the PR author instead of/in addition to the actor?  The reason I ask for this is that there are times where I need to re-run the action and I don't want to have to get dependabot to recreate the PR via `@dependabot recreate`, since that takes more time.

The author is available in the [PR event data](https://docs.github.com/en/rest/reference/pulls) and I'm able to access it in actions yml using `github.event.pull_request.user.login`

Happy to open a PR for this if desired

**Comment by djurre** [comment]
I'm running into this as well, I think it's more logical to just look at the PR author.

@jackson-miller-tbol Have you looked into this any further yet?

**Comment by mwaddell** [comment]
I'm running into this as well - pushing changes to the branch triggers the actions to rerun, but since I pushed the changes, I'm the actor instead of dependabot.

Getting the error message `PR is not from Dependabot, nothing to do.` doesn't really make sense when the PR *is* from dependabot...
