### ISSUE TITLE
Docs: Update Example to minimize Approval-notification-spam

### ISSUE THREAD

**Issue by fbartho** [dependabot/fetch-metadata#138]
This action has an example for how to enable auto-approve:

https://github.com/dependabot/fetch-metadata/blob/ffa0846490b6178282839adcc9f50954b247e373/README.md#L68-L72

In our repo and many repos, a previous approval is not invalidated by a rebase. And the default example causes dependabot to auto-approve every time it rebases that PR, this approval appears as an additional email for subscribed viewers. So, every rebase causes an email for the rebase and an email for the approval.

Proposed alternative command:
```bash
(gh pr status --json url -q '.needsReview.url?' | grep "$PR_URL" && gh pr review --approve "$PR_URL") || echo "PR already approved, skipping additional approvals to minimize emails/notification noise."
```

This alternative command would skip the approval if the PR in question isn't present in the `needsReview` section of the JSON output for `gh pr status`.

In addition to feedback on this docs update, if my command isn't optimal, I'd love for advice for a better command to use in its place. This requires relatively sophisticated shell-expressions, and I'd love to simplify this, and make it more robust.

**Comment by fbartho** [comment]
**Warning** Turns out, that that CLI command I proposed above doesn’t reliably work. So I’m still looking for a less-noisy solution to this problem if anybody has any advice?

**Comment by mwaddell** [comment]
@fbartho How about something like:

```bash
if [ $(gh pr status --json reviewDecision -q .currentBranch.reviewDecision) == "REVIEW_REQUIRED" ]; then 
  gh pr review --approve "$PR_URL"
else
  echo "PR already approved, skipping additional approvals to minimize emails/notification noise."
fi
```

**Comment by fbartho** [comment]
Thanks @mwaddell! That looks great. I’ll try that out.

**Comment by mwaddell** [comment]
@fbartho - let me know if that worked, if so, I'll update the example in our documentation.

**Comment by fbartho** [comment]
@mwaddell Looks like it's working! Thanks!

**Comment by fbartho** [comment]
@mwaddell Actually, I spoke too soon. Looks like a bash error?

![image](https://user-images.githubusercontent.com/209712/157125526-b4002f1a-6483-4ccd-8bde-61664d27394b.png)

**Comment by mwaddell** [comment]
I looked into it a bit more, and it looks like this approach won't work until they fix https://github.com/cli/cli/issues/575 

:-1:

**Comment by fbartho** [comment]
Bummer! Could I ensure our upstream is set for the repo or otherwise configure it for the purposes of this API call?

**Comment by mwaddell** [comment]
> Bummer! Could I ensure our upstream is set for the repo or otherwise configure it for the purposes of this API call?

I think I figured out a workaround - see if #188 works for you.  It looks a little silly to checkout the repo and then check it out again, but that's the only way to force the upstream to be set properly.

**Comment by fbartho** [comment]
I can confirm that #188 fixed this issue for us! -- It took a moment to get new Dependabot PRs to verify everything was working!

Obviously we'd still prefer a technique that doesn't require checking out the repo twice, but this is a good workaround for now.

Thanks!
