### ISSUE TITLE
Allow to use latest v1

### ISSUE THREAD

**Issue by MichaIng** [dependabot/fetch-metadata#180]
Currently, unlike with other GitHub actions, it is not possible to use the latest v1 via:
```
uses: dependabot/fetch-metadata@v1
```
=>
```
Error: Unable to resolve action `dependabot/fetch-metadata@v1`, unable to find version `v1`
```
It would be great it that was possible, so one does not need to (or gets offered to) update the workflow on every patch or minor version, where maintained compatibility is at least expected. Similarly `dependabot/fetch-metadata@v1.3` would be nice to work for a more conservative approach, pulling the latest patch version only.

I know this works with the official GitHub Actions actions, like `actions/checkout@v3`. They create and update additional release tags for this: https://github.com/actions/checkout/tags

**Comment by brrygrdn** [comment]
Hi @MichaIng thanks for this feedback, that's oversight on our part. I've added a `v1` tag and I'll update our release process to ensure it is moved forward.

**Comment by MichaIng** [comment]
That is great, many thanks!

**Comment by felipecrs** [comment]
Currently it points to v1.3.0 while it should point to v1.3.0, btw.

**Comment by MichaIng** [comment]
Right, v1.3.1 you mean 😉. I hope it doesn't cause too much additional hassle to keep the `v1` tag updated, probably as part of a release workflow 🙂.

**Comment by felipecrs** [comment]
Ideally it should be automated :)
