### ISSUE TITLE
Since today fetching metadata fails

### ISSUE THREAD

**Issue by MichaIng** [dependabot/fetch-metadata#184]
Not sure whether something changed on dependabot end, but fetching metadata suddenly fails since earlier today, observed on all three dependabot pull requests we received today:
```
Run dependabot/fetch-metadata@v1.3.0
  with:
    github-token: ***
Parsing Dependabot metadata
Error: PR does not contain metadata, nothing to do.
```
E.g. here: https://github.com/ravenclaw900/DietPi-Dashboard/actions/runs/2028340724

Probably related to today's core release? https://github.com/dependabot/dependabot-core/pull/4898

**Comment by mwaddell** [comment]
@MichaIng,`fetch-metadata` expects the branchname of dependabot branches to use the form:
`dependabot/{ecosystem}/{directory}/{dependency}`

However, starting 4 days ago, your branchnames are all:
`{4 character hex code}dependabot/{ecosystem}/{directory}/{dependency}`

This occurred the same day that you created a new branch called `dependabot` - I was not aware that doing that would impact the names of the generated branches, but it does seem unlikely this is a coincidence.  If you remove the `dependabot` branch from your repo, does the issue go away?

**Comment by MichaIng** [comment]
Great find, this totally makes sense. No I haven't recognised that dependabot branches have some 4 hex char prefix now that the `dependabot` branch exists, and indeed this will be the issue. I'll report back once the related PR has been merged and following dependabot PRs metadata work, but I'm pretty sure that's it 👍🙂.

**Comment by brrygrdn** [comment]
This is a slightly under-documented behaviour in Dependabot core, having a branch named `dependabot` effectively blocks the use of `dependabot/` in the git file system so we rescue it by using a random prefix for your branches.

**Comment by MichaIng** [comment]
Thanks for the clarification. Is this a general behaviour in Git or GitHub that a branch "name" prevents the creation of branches "name/*", as sort of a namespace blocker?
