### ISSUE TITLE
Metadata fields `alert-state`, `ghsa-id` & `cvss` are never populated when the manifest file is at the root

### ISSUE THREAD

**Issue by SalimBensiali** [dependabot/fetch-metadata#185]
If you look at https://github.com/SalimBensiali/le-blanc-jewellery/runs/5561937034?check_suite_focus=true, you would expect to see the relevant vulnerability alert metadata, but I am always getting the default data instead, ie:

```
outputs.alert-state: ''
outputs.ghsa-id: ''
outputs.cvss: 0
```

- I am using a PAT with enough permissions for successful GraphQL API calls
- I have double checked that the PR is indeed fixing a security vulnerability https://github.com/SalimBensiali/le-blanc-jewellery/pull/215

![image](https://user-images.githubusercontent.com/235000/159808402-8b8d0e4b-c38a-459a-928e-5c5dc304e90f.png)

**Comment by lindan-betterment** [comment]
I am experiencing the same issue.

**Comment by mwaddell** [comment]
@SalimBensiali your repository is not configured to use Dependabot security updates and alerts:

![image](https://user-images.githubusercontent.com/750244/160263478-b64fefe9-4bf0-428e-bc46-e93a0ed98542.png)

I updated the README (see #187) to make it explicit that this feature relies upon those being enabled.  My apologies for the confusion.

**Comment by SalimBensiali** [comment]
@mwaddell my repo does. Look at any previously closed dependabot alerts via the auto merge workflow https://github.com/SalimBensiali/le-blanc-jewellery/pulls?q=is%3Apr+is%3Aclosed

The issue I am reporting relates the v1.3.0 new features `alert-lookup`

**Comment by SalimBensiali** [comment]
I think you simply don't have the permissions to view them
![image](https://user-images.githubusercontent.com/235000/160265907-b3e6ded2-afa0-4c6d-b9d5-60d82c2ef3f4.png)

**Comment by SalimBensiali** [comment]
@mwaddell I managed to run the dry-run command which successfully return the missing metadata for me.
![image](https://user-images.githubusercontent.com/235000/160267087-8c309876-2ce3-4ebd-a61c-90ce642e5374.png)

Could it be because you `LOCAL_GITHUB_ACCESS_TOKEN` does not give you permission to to access the data? Which would be consistent with not seeing that dependabot security alerts and updates on https://github.com/SalimBensiali/le-blanc-jewellery/security.

**Comment by SalimBensiali** [comment]
The docs you are linking to #187 in (https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts#access-to--dependabot-alerts) does explain why you could not see any dependabot alerts on my repo.

> By default, we notify people with admin permissions in the affected repositories about new Dependabot alerts. GitHub never publicly discloses identified vulnerabilities for any repository. You can also make Dependabot alerts visible to additional people or teams working repositories that you own or have admin permissions for. For more information, see "[Managing security and analysis settings for your repository](https://docs.github.com/en/github/administering-a-repository/managing-security-and-analysis-settings-for-your-repository#granting-access-to-security-alerts)."

**Comment by SalimBensiali** [comment]
@mwaddell you could run the dry-run command off main and my branch and target a test repo you own to verify the bug and the fix. All you need is a repo with a manifest file in the root directory and any dependabot PR.

**Comment by mwaddell** [comment]
Thank you for the additional clarification - I understand now.  Thank you for the PR and for updating all the unit tests, I've reviewed and approved the changes for @brrygrdn to merge.

**Comment by SalimBensiali** [comment]
👍
