### ISSUE TITLE
Handle leading "v" in versions in a commit message

### ISSUE THREAD

**Issue by jonmcquillan** [dependabot/fetch-metadata#244]
eg `Bumps org/repo from v1.3.0 to v1.3.2.`  as a commit message does not populate the previous-version and new-version, so is also unable to calculate the proper update-type.  This makes the output not very useful for determining whether to auto merge a dependabot PR only on minor version changes or less for example.

**Comment by jonmcquillan** [comment]
Something like this maybe?  https://github.com/dependabot/fetch-metadata/pull/245

**Comment by jeffwidman** [comment]
Makes sense, this should get fixed.

Input: `Bumps org/repo from v1.3.0 to v1.3.2`

Expected output:
`previous-version: "v1.3.0"`
`new-version: "v1.3.2"`
`update-type: "version-update:semver-patch"`

In other words, the "handling" should strip the leading `v` when calculating the `update-type`, but not actually strip it when populating the final `"previous-version"` / `"new-version"`...
