### ISSUE TITLE
Warnings about `set-output` in the logs for v1.3.4 of this Action

### ISSUE THREAD

**Issue by ericcornelissen** [dependabot/fetch-metadata#277]
Using this Action at [v1.3.4] I'm getting various warnings that look like:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This seems to be due to [v1.3.4] using `@actions/core@v1.9.1`. On the `main` branch of this repository, since #272, this has already been bumped to `@actions/core@v1.10.0` which should resolve the warnings. As such, could a new version be releases so that the GitHub Action logs for this workflows using this action are clean again, thanks!

[v1.3.4]: https://github.com/dependabot/fetch-metadata/releases/tag/v1.3.4

**Comment by jeffwidman** [comment]
This was fixed in https://github.com/dependabot/fetch-metadata/releases/tag/v1.3.5 but I forgot to close this.

**Comment by jeffwidman** [comment]
And thanks for the heads up @ericcornelissen
