### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jamime** [dependabot/fetch-metadata#323]
It would be great to re-use some of this logic in a [probot](https://probot.github.io/) bot. Would it be possible to publish this to npm?

**Comment by jeffwidman** [comment]
👋 thanks for dropping by.

Can you clarify a little more:
* how you'd want to use this? Ie, what would your bot do?
* And which parts of this logic would you need access to?

**Comment by jeffwidman** [comment]
Closing due to lack of response.
