### ISSUE TITLE
Migrate to node 18 whenever Actions adds support for it.

### ISSUE THREAD

**Issue by yeikel** [dependabot/fetch-metadata#335]
See https://github.com/dependabot/fetch-metadata/issues/334#issuecomment-1500541174

**Comment by jeffwidman** [comment]
Based on https://github.com/dependabot/fetch-metadata/issues/334#issuecomment-1500679673 this is blocked until Actions starts shipping `node18`. There's no timeline that I'm aware of for that, so it could be a while. 🤷‍♂️

**Comment by jeffwidman** [comment]
@yeikel can this be closed now that https://github.com/dependabot/fetch-metadata/pull/443 is shipped in https://github.com/dependabot/fetch-metadata/releases/tag/v2.0.0?
