### ISSUE TITLE
Auto-merge not adhering to Branch Protection Rules

### ISSUE THREAD

**Issue by smcvb** [dependabot/fetch-metadata#346]
First and foremost, I am not 100% confident this is the right place to report this in.
So, if not, feel free to move my request or me somewhere else.

Now, to the predicament at hand.
I maintain an open-source organization with several repositories utilizing Dependabot to ensure all our dependencies stay up to date.
As manual merging became too much of a burden to the team, I investigated how to employ auto-merge in our environment.

This investigation landed me on the [Automating Dependabot with GitHub Actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions) page that describes how to achieve just that.
After going through the description step by step, I assumed everything was in place.
Thus I set an (in my case, dedicated) YAML for the auto-approval and auto-merge procedures and added branch protection rules for `dependabot` specific pull requests.

Although the GitHub configuration matches the branch protection rules with the dependabot PRs, some are merged regardless of whether the task succeeds.

After noticing this predicament, I went on a second investigation to figure out what I was missing.
This eventually led me to the `README.md` of this project, which also describes the [auto-merge capabilities](https://github.com/dependabot/fetch-metadata#enabling-auto-merge).

Furthermore, I noticed a slight discrepancy between this project's readme and the GitHub docs page.
The latter states the following on [auto-merge](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request):

> If you want to allow maintainers to mark certain pull requests for auto-merge, you can use GitHub's auto-merge functionality. 
> This enables the pull request to be merged when any tests and approvals required by the branch protection rules are successfully met. 
> For more information, see "[Automatically merging a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request)" and "[Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)."
> You can instead use GitHub Actions and the GitHub CLI. Here is an example that auto merges all patch updates to my-dependency:

Whereas this project's readme states:

> If you are using [the auto-merge feature](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) on your repository, you can set up an action that will enable Dependabot PRs to merge once CI and other [branch protection rules](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) are met. (Note that you must use a [personal access token (PAT)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) when executing the merge instruction.)

The former seems to state that GitHub Action can be used *instead* of branch protection rules, whereas the latter describes the necessity of combining both.
Aside from being interested in the actual approach, I'm also wondering why my branch protection rules do not seem to block the auto-merge.

If anybody reading this can help me with that or guide me to somebody who does know, that would be very much appreciated.

**Comment by jeffwidman** [comment]
Given this is happening on an open source project, can you link to it as well as provide screenshots of the branch protection rules you've set in the repo settings?

**Comment by smcvb** [comment]
@jeffwidman, I don't want to push, but I am wondering whether there's any information I can go on concerning this predicament.
Do you per chance have an update for me? Thanks in advance for your time! :bow:

**Comment by TiddoLangerak** [comment]
Your branch protection should be set up on your _target_ branch, not on your source (PR) branch. I.e. it protects the branch you merge into, not the branch you merge from. 

In your first screenshot you've shown to set up branch protection on the `dependabot/**/*` branches, but you should set it up on your `master` branch instead.

(It's an old issue, so I'm sure you've figured this out by now, just wanted to leave a comment for any other passerby that might run into the same issue).

**Comment by smcvb** [comment]
Aaah darn, I completely forgot about this issue...

You're right, @TiddoLangerak, I already figured this out myself.
I should've shared that finding here, though. Thanks for doing that for me :pray: 

I'll hereby close this issue as resolved.
