### ISSUE TITLE
Readme example contains invalid workflow syntax

### ISSUE THREAD

**Issue by CloudNStoyan** [dependabot/fetch-metadata#560]
The `if` conditional inside the README's example should be before `steps` and not `jobs`
https://github.com/dependabot/fetch-metadata/blob/b0d0393a82702c1819b5ae7ad6ea780cd8c18aae/README.md?plain=1#L19-L37
Currently this is not valid workflow syntax as far as I can tell :)

**Comment by Nishnha** [comment]
Fixed by [fix readme action example #563](https://github.com/dependabot/fetch-metadata/pull/563)
