### ISSUE TITLE
Flag security related dependabot PRs

### ISSUE THREAD

**Issue by SalimBensiali** [dependabot/fetch-metadata#84]
Hi and thanks for this action.

I was wondering it the metadata had information about whether a PR raised by dependabot was due to a security alert/vulnerability.

Thanks.
Salim

**Comment by mwaddell** [comment]
I would be happy to work on this, but I can't figure out any way to get access to the list of current [repository_vulnerability_alert](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_vulnerability_alert) entries through the rest api.

The only items I see in the api are related to [checking whether vulnerability alerts are enabled or not](https://octokit.github.io/rest.js/v18#repos-check-vulnerability-alerts), but I can't find a way to actually list the alerts.  

Anyone know of a way to do this?

**Comment by mwaddell** [comment]
Ah, it looks like it's only available through the GraphQL API, not the REST one.  I'm not as familiar with that one, but I'll poke at it a bit tomorrow.
